frontend/admin/admin/Controllers/CareerMapsController.cs
using admin.Api.Model.Response;
using admin.Services;
using admin.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace admin.Controllers
{
    public class CareerMapsController : Controller
    {
        private CareerMapsService _service;

        public CareerMapsController()
        {
            _service = new CareerMapsService();
            
        }

        public ActionResult Index()
        {
            return View(_service.GetAllCareers());
        }

        public ActionResult CompanyPositionsCareerMapDetail(int careerMapId)
        {
            var ret = _service.LoadCompanyPositionsFromCareerMapId(careerMapId);
            return View(ret);
        }

        public ActionResult RequirementsCompanyPositionDetail(int careerMapId, int companyPositionId)
        {
            var ret = _service.LoadRequirementsFromCompanyPositionId(careerMapId, companyPositionId);
            return View(ret);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CareerMapResponse careerMap)
        {
            var ret = _service.Insert(careerMap);
            if (ret)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult AssociatePositions(int careerMapId)
        {
            var availablePositions = new List<CompanyPositionInfo>();
            var unavailablePositions = new List<CompanyPositionInfo>();
            var init = new CompanyPositionListResponse();
            var career = _service.GetAllCareers().Find(x => x.CareerMapId == careerMapId);

            if(career != null)
            {
                try
                {
                    var _serviceCompanyPosition = new CompanyPositionService();

                    var existingPositions = _service.LoadCompanyPositionsFromCareerMapId(careerMapId);
                    var all = _serviceCompanyPosition.GetAllPositions();

                    foreach (var pos in all)
                    {
                        var info = new CompanyPositionInfo()
                        {
                            CompanyPositionId = pos.CompanyPositionId,
                            CompanyPositionName = pos.CompanyPositionName
                        };

                        if (existingPositions.CompanyPositionResponseList.Find(x => x.CompanyPositionInfo.CompanyPositionId == pos.CompanyPositionId) != null)
                        {
                            unavailablePositions.Add(info);
                        }
                        else
                        {
                            availablePositions.Add(info);
                        }
                    }

                }
                catch (Exception) { /* throw; */ }
            }

            ViewBag.AvailablePositions = availablePositions;
            ViewBag.UnavailablePositions = unavailablePositions;

            init.CareerMapResponse = career == null ? new CareerMapResponse() : career;
            
            return View(init);
        }

        [HttpPost]
        public ActionResult AssociatePositions(CompanyPositionListResponse positions)
        {
            var ret = _service.AssociatePositions(positions);
            if (ret)
            {
                return RedirectToAction("CompanyPositionsCareerMapDetail", new { careerMapId = positions.CareerMapResponse.CareerMapId });
            }
            else
            {
                return View();
            }
        }
    }
}

frontend/admin/admin/Controllers/TestsController.cs
using admin.Api.Model;
using admin.Api.Model.Response;
using admin.Api.Service;
using admin.Services;
using admin.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace admin.Controllers
{
    public class TestsController : Controller
    {
        private Services.TestService _service { get; set; }

        public TestsController()
        {
            _service = new Services.TestService();
        }


        // GET: CarrermapsController
        public ActionResult TestsByRequirement(int requirementId)
        {
            ViewBag.requirementId = requirementId;
            return View(_service.GetAllTestsByRequirementId(requirementId));
        }

        [HttpGet]
        public ActionResult Create(int requirementId)
        {
            ViewBag.requirementId = requirementId;
            return View();
        }

        [HttpPost]
        public ActionResult Create(MTest test)
        {
            var res = _service.Insert(test);

            if (res)
            {
                return RedirectToAction("TestsByRequirement", new { requirementId = test.RequirementId });
            }
            else
            {
                ViewBag.requirementId = test.RequirementId;
                return View();
            }
        }

        // GET: TestByID
        public ActionResult Details(int testId)
        {
            return View(_service.GetTestById(testId));
        }

        //[HttpPost]
        //public ActionResult Create(/*TestInfo test*/)
        //{
        //    //var ret = _service.AddTest(test);
        //    //if (ret)
        //    //{
        //    //    return RedirectToAction("Index");
        //    //}
        //    //else
        //    //{
        //        return View();
        //    //}
        //}



        ////private CompanyPositionService _service { get; set; }

        //public RequirementsController()
        //{
        //_service = new CompanyPositionService();
        //}

        //// GET: CompanyPositionController
        //public ActionResult Index() 
        //{
        //IEnumerable<CompanyPositionVM> positions;
        //try
        //{
        //    CompanyPositionListVM cmCompanyPositions = _service.GetAllCompanyPositions().Result;
        //    //lblBreadcrumb.Text = $"{cmCompanyPositions.CareerMapVm.CareerMapName}";

        //    positions = new List<CompanyPositionVM>(cmCompanyPositions.CompanyPositionVmList);
        //}
        //catch (Exception)
        //{
        //    positions = new List<CompanyPositionVM>();
        //    ModelState.AddModelError(string.Empty, "Erro no servidor. Contate o Administrador.");
        //}

        //    return View("This is index");
        //}

        ////public ActionResult Index(int careerId) 
        ////{
        ////    IEnumerable<CompanyPositionVM> positions;
        ////    try
        ////    {
        ////        CompanyPositionListVM cmCompanyPositions = _service.GetAllCompanyPositions().Result;
        ////        //lblBreadcrumb.Text = $"{cmCompanyPositions.CareerMapVm.CareerMapName}";

        ////        positions = new List<CompanyPositionVM>(cmCompanyPositions.CompanyPositionVmList);
        ////    }
        ////    catch (Exception)
        ////    {
        ////        positions = new List<CompanyPositionVM>();
        ////        ModelState.AddModelError(string.Empty, "Erro no servidor. Contate o Administrador.");
        ////    }

        ////    return View(positions);
        ////}





        //public ActionResult Index0()
        //{
        //    //return View(_service);

        //    IEnumerable<CompanyPositionService> contatos = null;

        //    using (var client = new HttpClient())
        //    {
        //        client.BaseAddress = new Uri("https://localhost:7149/api/careerMaps/1/companyPositions");

        //        //HTTP GET
        //        var responseTask = client.GetAsync("contatos");
        //        responseTask.Wait();
        //        var result = responseTask.Result;

        //        if (result.IsSuccessStatusCode)
        //        {
        //            var readTask = result.Content.ReadAsAsync<IList<CompanyPositionService>>();
        //            readTask.Wait();
        //            contatos = readTask.Result;
        //        }
        //        else
        //        {
        //            contatos = Enumerable.Empty<CompanyPositionService>();
        //            ModelState.AddModelError(string.Empty, "Erro no servidor. Contate o Administrador.");
        //        }
        //        return View(contatos);
        //    }
        //}    

        //// GET: CompanyPositionController/Details/5
        //public ActionResult Informacao(int id)
        //{
        //    return View();
        //}

        //// GET: CompanyPositionController/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: CompanyPositionController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: CompanyPositionController/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: CompanyPositionController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: CompanyPositionController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: CompanyPositionController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

frontend/admin/admin/Views/CareerMaps/AssociatePositions.cshtml
@using admin.Api.Model.Response;
@model admin.Api.Model.Response.CompanyPositionListResponse

@{
    ViewData["Title"] = "Incluir associações de Cargos à Mapa de Carreira";

    var parms = new Dictionary<string, string>
    {
        { "careerMapId", $"{Model.CareerMapResponse.CareerMapId}"}
    };
}


@*@Model.CareerMapResponse.CareerMapId*@

<h4>@ViewData["Title"]</h4>
<hr />

<form asp-action="AssociatePositions">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    @*<div class="col-md-4">*@
        <div class="form-group">
            <input type="hidden" asp-for="CareerMapResponse.CareerMapId" />

            <label asp-for="CareerMapResponse.CareerMapName" class="control-label">Mapa de carreira</label>
            <input disabled asp-for="CareerMapResponse.CareerMapName" class="form-control" />
            <span asp-validation-for="CareerMapResponse.CareerMapName" class="text-danger"></span>
        </div>
    @*</div>*@

    <div class="form-group mt-3">
        <label for="posicao">Cargos disponíveis</label>


        @if (ViewBag.AvailablePositions != null)
        {
            var list = ((List<CompanyPositionInfo>)ViewBag.AvailablePositions);
@*            for (int i = 0; i < list.Count; i++)
            {
                var posicao = list[i];
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" id="posicao-@(i).CompanyPositionId" name="CompanyPositionResponseList[@(i)].CompanyPositionInfo.CompanyPositionId" value="@posicao.CompanyPositionId" />
                    <label class="form-check-label" for="posicao-@posicao.CompanyPositionId">@posicao.CompanyPositionName</label>
                </div>
            }*@
                    @*<input type="hidden" id="posicao-@(i).CompanyPositionName" name="CompanyPositionResponseList[@(i)].CompanyPositionInfo.CompanyPositionName" value="@posicao.CompanyPositionName" />*@



            <select class="form-control" id="posicao" name="CompanyPositionResponseList[0].CompanyPositionInfo.CompanyPositionId">
                @*<option value="">Selecione o cargo</option>*@
                @if(list == null || list.Count == 0)
                {
                    <option value="">Não existem cargos disponíveis para associação.</option>
                }
                else
                {
                    @foreach (var posicao in list)
                    {
                        <option value="@posicao.CompanyPositionId">@posicao.CompanyPositionName</option>
                    }
                }
            </select>
        }


    </div>

@*
    <div class="form-group mt-4">
        <label for="posicoes">Cargos disponíveis</label>
        <br />

        @if(ViewBag.AvailablePositions != null)
        {
            var list = ((List<CompanyPositionInfo>)ViewBag.AvailablePositions);
            for (int i = 0; i < list.Count; i++)
            {
                var posicao = list[i];
                <div class="form-check form-check-inline">
                    <input type="hidden" id="posicao-@(i).CompanyPositionName" name="CompanyPositionResponseList[@(i)].CompanyPositionInfo.CompanyPositionName" value="@posicao.CompanyPositionName" />
                    <input class="form-check-input" type="checkbox" id="posicao-@(i).CompanyPositionId" name="CompanyPositionResponseList[@(i)].CompanyPositionInfo.CompanyPositionId" value="@posicao.CompanyPositionId" />
                    <label class="form-check-label" for="posicao-@posicao.CompanyPositionId">@posicao.CompanyPositionName</label>
                </div>
            }
        }*@

@*        @if (ViewBag.AvailablePositions != null)
        {
            var list = ((List<CompanyPositionInfo>)ViewBag.AvailablePositions);
            for (int i = 0; i < list.Count; i++)
            {
                var posicao = list[i];
                <div class="form-check form-check-inline">
                    <input type="hidden" id="posicao-@(i).CompanyPositionName" name="CompanyPositionResponseList[@(i)].CompanyPositionInfo.CompanyPositionName" value="@posicao.CompanyPositionName" />
                    <input class="form-check-input" type="checkbox" id="posicao-@(i).CompanyPositionId" name="CompanyPositionResponseList[@(i)].CompanyPositionInfo.CompanyPositionId" value="@posicao.CompanyPositionId" />
                    <label class="form-check-label" for="posicao-@posicao.CompanyPositionId">@posicao.CompanyPositionName</label>
                </div>
            }
        }
    </div>
        *@

    @if (ViewBag.UnavailablePositions != null && ViewBag.UnavailablePositions.Count > 0)
    {
    <div class="form-group mt-3">
        <label for="posicoes">Cargos já associados</label>
        <br />

        @foreach (var posicao in ViewBag.UnavailablePositions)
        {
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" id="un-posicao-@posicao.CompanyPositionId" disabled checked value="@posicao.CompanyPositionId" />
                <label class="form-check-label" for="posicao-@posicao.CompanyPositionId">@posicao.CompanyPositionName</label>
            </div>
        }
    </div>
    }


    @*<div class="col-md-12">*@
        <div class="form-row mt-4 col-6">
            <div class="form-group">
            @*<div class="col">*@
                <input type="submit" value="Salvar" class="btn btn-md btn-success col-5"/>
            @*</div>*@
            @*<span class="col col-md-2">&nbsp;</span> *@
            @*<div class="col">*@

            <a class="col btn btn-md btn-outline-danger offset-1 col-5" asp-action="CompanyPositionsCareerMapDetail" asp-all-route-data="parms" >Cancelar</a>
            @*</div>*@
            </div>
        </div>
    @*</div>*@
</form>



@*


<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="CareerMapResponse.CareerMapName" class="control-label">Mapa de carreira</label>
                <input disabled asp-for="CareerMapResponse.CareerMapName" class="form-control" />
                <span asp-validation-for="CareerMapResponse.CareerMapName" class="text-danger"></span>
            </div>
        </div>
    </div>


    <div class="row mt-md-4">
        <div class="col-md-12">
            <div class="row">
                <input type="submit" value="Salvar" class="btn btn-md btn-success col-md-5" />
                <span class="col-md-2"></span>
                <a class="btn btn-md btn-outline-danger col-md-5" asp-action="Index">Cancelar</a>
            </div>
        </div>
    </div>
</form>
*@


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

frontend/admin/admin/Views/CareerMaps/CompanyPositionsCareerMapDetail.cshtml
@model admin.Api.Model.Response.CompanyPositionListResponse
@{
    ViewBag.Title = "Carreira - " + Model.CareerMapResponse.CareerMapName;
}

<h4>Cargos da carreira</h4>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="@Url.Action("Index", "CareerMaps")">Mapas de carreira</a></li>
        <li class="breadcrumb-item active" aria-current="page">@Model.CareerMapResponse.CareerMapName</li>
    </ol>
</nav>

<div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <button class="btn btn-outline-dark me-md-2" type="button" onclick="location.href='@Url.Action("AssociatePositions", new { careerMapId = Model.CareerMapResponse.CareerMapId } )'">Associar cargos</button>
</div>

<table class="table table-striped datatables">
    <thead>
        <tr>
            <th>
                Cargos
            </th>
            <th class="w-25">
            </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model.CompanyPositionResponseList)
        {
        <tr>
            <td>
                @Html.HiddenFor(modelItem => item.CompanyPositionInfo.CompanyPositionId)
                @Html.DisplayFor(modelItem => item.CompanyPositionInfo.CompanyPositionName)
            </td>
            <td>
                    <button class="btn btn-outline-info btn-sm" onclick="location.href='@Url.Action("RequirementsCompanyPositionDetail", new { careerMapId = Model.CareerMapResponse.CareerMapId, companyPositionId = item.CompanyPositionInfo.CompanyPositionId })'">Requisitos</button>
            </td>
        </tr>
        }
       @* <tr>
            <td>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            </td>
        </tr>*@
    </tbody>
</table>

<style>
.btn-details {
  background-color: #007bff;
  color: #fff;
  border: none;
  padding: 8px 8px;
  border-radius: 4px;
  cursor: pointer;
}

.btn-details:hover {
  background-color: #0069d9;
}
</style>

frontend/admin/admin/Views/CareerMaps/Create.cshtml
@model admin.Api.Model.Response.CareerMapResponse

@{
    ViewData["Title"] = "Novo Mapa de Carreira";
}

<h4>@ViewData["Title"]</h4>
<hr />

<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-md-4">
            <label asp-for="CareerMapName" class="control-label">Mapa de carreira</label>
            <input asp-for="CareerMapName" class="form-control" />
            <span asp-validation-for="CareerMapName" class="text-danger"></span>
        </div>
    </div>

    <div class="row mt-md-4">
        <div class="col-md-4">
            <input type="submit" value="Salvar" class="btn btn-md btn-success col-md-5" />
            <span class="col-md-2"></span>
            <a class="btn btn-md btn-outline-danger col-md-5" asp-action="Index">Cancelar</a>
        </div>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

frontend/admin/admin/Views/CareerMaps/Details - Cópia.cshtml
@*@model IEnumerable<admin.ViewModels.CareerMapVM>
@{
    ViewBag.Title = "Index";
}*@
@*<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Desenvolvimento Backend</a></li>
        <li class="breadcrumb-item active" aria-current="page">Carreiras</li>
    </ol>
    <h1>Desenvolvimento Backend</h1>

    <button class="btn-details" onclick="location.href='@Url.Action("Informacao")'">Exibir</button>

     
    <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" id="redirecionar" onchange="irParaPagina()">  
        <option selected>Analista Júnior</option>
        <option value="/CareerMaps/Informacao">C#</option>
        <option value="carreiras.html">SQL</option>
        <option value="carreiras.html">AWS</option>
        <option value="carreiras.html">Java</option>
        <option value="/CareerMaps/Informacao">Azure</option>
    </select>
    <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" id="redirecionar" onchange="irParaPagina()">
        <option selected>Analista Pleno </option>
        <option value="carreiras.html">C#</option>
        <option value="carreiras.html">SQL</option>
        <option value="carreiras.html">AWS</option>
        <option value="carreiras.html">Java</option>
        <option value="/CareerMaps/Informacao">Azure</option>
    </select>
    <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" id="redirecionar" onchange="irParaPagina()">
        <option selected>Analista Senior</option>
        <option value="carreiras.html">C#</option>
        <option value="carreiras.html">SQL</option>
        <option value="carreiras.html">AWS</option>
        <option value="carreiras.html">Java</option>
        <option value="/CareerMaps/Informacao">Azure</option>
    </select>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <button class="btn btn-primary" type="button" onclick="history.back()">Button</button>
    </div>
</nav>*@

@*<script src="scripts/main.js"></script>
<script>
function irParaPagina() {
  var select = document.getElementById("redirecionar");
  var selectedOption = select.options[select.selectedIndex];
  if (selectedOption.value !== "") {
    window.location = selectedOption.value;
  }
}
CompanyPositionRequirementsVM
</script>*@


@model admin.Api.Model.Response.CompanyPositionListResponse
@{
    ViewBag.Title = "Carreira - " + Model.CareerMapResponse.CareerMapName;//  @model. CareerMapVm.CareerMapName;
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">@Model.CareerMapResponse.CareerMapName</li>
    </ol>
    @*<h2>Mapa de Carreira</h2>*@
@*    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <button class="btn btn-primary me-md-2" type="button">Adicionar Mapa</button>
    </div>*@


    <table class="table">
        <tr>
            <th>
                Id
            </th>
            <th>
                Career name
            </th>
            <th>
                Action
            </th>
        </tr>

        @foreach (var item in Model.CompanyPositionResponseList)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CompanyPositionInfo.CompanyPositionId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CompanyPositionInfo.CompanyPositionName)
                </td>
                <td>
                    <button class="btn-details" onclick="location.href='@Url.Action("Informacao", new { id = item.CompanyPositionInfo.CompanyPositionId })'">Exibir</button>
                </td>
            </tr>
        }
    </table>   
</nav>



<style>
.btn-details {
  background-color: #007bff;
  color: #fff;
  border: none;
  padding: 8px 8px;
  border-radius: 4px;
  cursor: pointer;
}

.btn-details:hover {
  background-color: #0069d9;
}
</style>


            

frontend/admin/admin/Views/CareerMaps/Details.cshtml
@*@model IEnumerable<admin.ViewModels.CareerMapVM>
@{
    ViewBag.Title = "Index";
}*@
@*<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Desenvolvimento Backend</a></li>
        <li class="breadcrumb-item active" aria-current="page">Carreiras</li>
    </ol>
    <h1>Desenvolvimento Backend</h1>

    <button class="btn-details" onclick="location.href='@Url.Action("Informacao")'">Exibir</button>

     
    <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" id="redirecionar" onchange="irParaPagina()">  
        <option selected>Analista Júnior</option>
        <option value="/CareerMaps/Informacao">C#</option>
        <option value="carreiras.html">SQL</option>
        <option value="carreiras.html">AWS</option>
        <option value="carreiras.html">Java</option>
        <option value="/CareerMaps/Informacao">Azure</option>
    </select>
    <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" id="redirecionar" onchange="irParaPagina()">
        <option selected>Analista Pleno </option>
        <option value="carreiras.html">C#</option>
        <option value="carreiras.html">SQL</option>
        <option value="carreiras.html">AWS</option>
        <option value="carreiras.html">Java</option>
        <option value="/CareerMaps/Informacao">Azure</option>
    </select>
    <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" id="redirecionar" onchange="irParaPagina()">
        <option selected>Analista Senior</option>
        <option value="carreiras.html">C#</option>
        <option value="carreiras.html">SQL</option>
        <option value="carreiras.html">AWS</option>
        <option value="carreiras.html">Java</option>
        <option value="/CareerMaps/Informacao">Azure</option>
    </select>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <button class="btn btn-primary" type="button" onclick="history.back()">Button</button>
    </div>
</nav>*@

@*<script src="scripts/main.js"></script>
<script>
function irParaPagina() {
  var select = document.getElementById("redirecionar");
  var selectedOption = select.options[select.selectedIndex];
  if (selectedOption.value !== "") {
    window.location = selectedOption.value;
  }
}
CompanyPositionRequirementsVM
</script>*@


@model admin.Api.Model.Response.CompanyPositionListResponse
@{
    ViewBag.Title = "Carreira - " + Model.CareerMapResponse.CareerMapName;//  @model. CareerMapVm.CareerMapName;
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">@Model.CareerMapResponse.CareerMapName</li>
    </ol>
    @*<h2>Mapa de Carreira</h2>*@
@*    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <button class="btn btn-primary me-md-2" type="button">Adicionar Mapa</button>
    </div>*@


    <table class="table">
        <tr>
            <th>
                Id
            </th>
            <th>
                Career name
            </th>
            <th>
                Action
            </th>
        </tr>

        @foreach (var item in Model.CompanyPositionResponseList)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CompanyPositionInfo.CompanyPositionId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CompanyPositionInfo.CompanyPositionName)
                </td>
                <td>
                    <button class="btn-details" onclick="location.href='@Url.Action("Informacao", new { id = item.CompanyPositionInfo.CompanyPositionId })'">Exibir</button>
                </td>
            </tr>
        }
        <tr>
            <td>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            </td>
        </tr>
    </table>   
</nav>



<style>
.btn-details {
  background-color: #007bff;
  color: #fff;
  border: none;
  padding: 8px 8px;
  border-radius: 4px;
  cursor: pointer;
}

.btn-details:hover {
  background-color: #0069d9;
}
</style>


            

frontend/admin/admin/Views/CareerMaps/RequirementsCompanyPositionDetail.cshtml
@model admin.Api.Model.Response.RequirementListResponse
@{
    ViewBag.Title = "Cargo - "; //+ Model.CompanyPositionInfo.CompanyPositionName;
}

<h4>Requisitos do cargo</h4>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item "><a href="@Url.Action("Index", "CareerMaps")">Mapas de carreira</a></li>
        <li class="breadcrumb-item"><a href="@Url.Action("CompanyPositionsCareerMapDetail", "CareerMaps", new { careerMapId = Model.CareerMap.CareerMapId })">@Model.CareerMap.CareerMapName</a></li>
        <li class="breadcrumb-item active">@Model.CompanyPositionInfo.CompanyPositionName</li>
    </ol>
</nav>

<div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <button class="btn btn-outline-dark me-md-2" type="button" onclick="location.href='@Url.Action("AssociateRequirements", new { careerMapId = Model.CareerMap.CareerMapId, companyPositionId=Model.CompanyPositionInfo.CompanyPositionId } )'">Associar requisito</button>
</div>

<table class="table table-striped datatables">
    <thead>
        <tr>
            <th>
                Requisito
            </th>
            <th class="w-25">
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Requirements)
        {
            <tr>
                <td>
                    @Html.HiddenFor(modelItem => item.RequirementInfo.RequirementId)
                    @Html.DisplayFor(modelItem => item.RequirementInfo.RequirementName)
                </td>
                <td>
                    <button class="btn btn-outline-info btn-sm" onclick="location.href='@Url.Action("TestsByRequirement", "Tests", new { requirementId = item.RequirementInfo.RequirementId })'">Testes</button>
                </td>
            </tr>
        }
       @* <tr>
            <td>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            </td>
        </tr>*@
    </tbody>
</table>

<style>
    .btn-details {
        background-color: #007bff;
        color: #fff;
        border: none;
        padding: 8px 8px;
        border-radius: 4px;
        cursor: pointer;
    }

        .btn-details:hover {
            background-color: #0069d9;
        }
</style>