frontend/admin/admin/Controllers/CareerMapsController.cs
using admin.Api.Model.Response;
using admin.Services;
using admin.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace admin.Controllers
{
    public class CareerMapsController : Controller
    {
        private CareerMapsService _service;

        public CareerMapsController()
        {
            _service = new CareerMapsService();
            
        }

        public ActionResult Index()
        {
            return View(_service.GetAllCareers());
        }

        public ActionResult CompanyPositionsCareerMapDetail(int careerMapId)
        {
            var ret = _service.LoadCompanyPositionsFromCareerMapId(careerMapId);
            return View(ret);
        }

        public ActionResult RequirementsCompanyPositionDetail(int careerMapId, int companyPositionId)
        {
            var ret = _service.LoadRequirementsFromCompanyPositionId(careerMapId, companyPositionId);
            return View(ret);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CareerMapResponse careerMap)
        {
            var ret = _service.Insert(careerMap);
            if (ret)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult AssociatePositions(int careerMapId)
        {
            var availablePositions = new List<CompanyPositionInfo>();
            var unavailablePositions = new List<CompanyPositionInfo>();
            var init = new CompanyPositionListResponse();
            var career = _service.GetAllCareers().Find(x => x.CareerMapId == careerMapId);

            if(career != null)
            {
                try
                {
                    var _serviceCompanyPosition = new CompanyPositionService();

                    var existingPositions = _service.LoadCompanyPositionsFromCareerMapId(careerMapId);
                    var all = _serviceCompanyPosition.GetAllPositions();

                    foreach (var pos in all)
                    {
                        var info = new CompanyPositionInfo()
                        {
                            CompanyPositionId = pos.CompanyPositionId,
                            CompanyPositionName = pos.CompanyPositionName
                        };

                        if (existingPositions.CompanyPositionResponseList.Find(x => x.CompanyPositionInfo.CompanyPositionId == pos.CompanyPositionId) != null)
                        {
                            unavailablePositions.Add(info);
                        }
                        else
                        {
                            availablePositions.Add(info);
                        }
                    }

                }
                catch (Exception) { /* throw; */ }
            }

            ViewBag.AvailablePositions = availablePositions;
            ViewBag.UnavailablePositions = unavailablePositions;

            init.CareerMapResponse = career == null ? new CareerMapResponse() : career;
            
            return View(init);
        }

        [HttpPost]
        public ActionResult AssociatePositions(CompanyPositionListResponse positions)
        {
            var ret = _service.AssociatePositions(positions);
            if (ret)
            {
                return RedirectToAction("CompanyPositionsCareerMapDetail", new { careerMapId = positions.CareerMapResponse.CareerMapId });
            }
            else
            {
                return View();
            }
        }
    }
}

frontend/admin/admin/Controllers/CompanyPositionController.cs
using admin.Api.Model.Response;
using admin.Services;
using admin.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using api = admin.Api.Service;

namespace admin.Controllers
{
    public class CompanyPositionController : Controller
    {
        private CompanyPositionService _service { get; set; }

        public CompanyPositionController()
        {
            _service = new CompanyPositionService();
        }


        // GET: CarrermapsController
        public ActionResult Index()
        {
            return View(_service.GetAllPositions());
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CompanyPositionInfo companyPosition)
        {
            var ret = _service.Insert(companyPosition);
            if (ret)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        //        [HttpGet]
        //public ActionResult AssociateRequirements(int careerMapId, int companyPositionId)
        //{
        //    var availableRequirements = new List<CompanyPositionInfo>();
        //    var unavailableRequirements = new List<CompanyPositionInfo>();
        //    var init = new CompanyPositionListResponse();
        //    var position = _service.GetAllPositions().Find(x => x.CompanyPositionId == companyPositionId && x.ParentCareerMapVm.CareerMapId == careerMapId);

        //    if (position != null)
        //    {
        //        try
        //        {
        //            var _serviceCompanyPosition = new CompanyPositionService();

        //            var existingPositions = _service.LoadCompanyPositionsFromCareerMapId(careerMapId);
        //            var all = _serviceCompanyPosition.GetAllPositions();

        //            foreach (var pos in all)
        //            {
        //                var info = new CompanyPositionInfo()
        //                {
        //                    CompanyPositionId = pos.CompanyPositionId,
        //                    CompanyPositionName = pos.CompanyPositionName
        //                };

        //                if (existingPositions.CompanyPositionResponseList.Find(x => x.CompanyPositionInfo.CompanyPositionId == pos.CompanyPositionId) != null)
        //                {
        //                    unavailableRequirements.Add(info);
        //                }
        //                else
        //                {
        //                    availableRequirements.Add(info);
        //                }
        //            }

        //        }
        //        catch (Exception) { /* throw; */ }
        //    }

        //    ViewBag.AvailablePositions = availableRequirements;
        //    ViewBag.UnavailablePositions = unavailableRequirements;

        //    init.CareerMapResponse = position == null ? new CareerMapResponse() : position;

        //    return View(init);
        //}

        //[HttpPost]
        //public ActionResult AssociatePositions(CompanyPositionListResponse positions)
        //{
        //    var ret = _service.AssociatePositions(positions);
        //    if (ret)
        //    {
        //        return RedirectToAction("CompanyPositionsCareerMapDetail", new { careerMapId = positions.CareerMapResponse.CareerMapId });
        //    }
        //    else
        //    {
        //        return View();
        //    }
        //}
    }
}

frontend/admin/admin/Controllers/RequirementsController.cs
using admin.Api.Model.Response;
using admin.Api.Service;
using admin.Services;
using admin.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PagedList;

namespace admin.Controllers
{
    public class RequirementsController : Controller
    {
        private Services.RequirementService _service { get; set; }

        public RequirementsController()
        {
            _service = new Services.RequirementService();
        }
                     

        public ActionResult Index(int pagina = 1, string sortOrder = null, string currentFilter = null, int contador = 0)
        {
            var result = pagina;
            int paginaT = 0;
            int paginaN = 0;
            for (var i = 1; i <= 6; i++)
            {
                if (result == i)
                {
                    paginaT = i;
                    paginaN = 20;
                    break;
                }
            }
            var retorno = _service.GetAllRequirements();
            var listaAlunos = retorno.ToList();                    
            return View(listaAlunos.ToPagedList(paginaT, paginaN));
        }          

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(RequirementInfo requirement)
        {
            var ret = _service.AddRequirement(requirement);
            if (ret)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }



        ////private CompanyPositionService _service { get; set; }

        //public RequirementsController()
        //{
        //_service = new CompanyPositionService();
        //}

        //// GET: CompanyPositionController
        //public ActionResult Index() 
        //{
        //IEnumerable<CompanyPositionVM> positions;
        //try
        //{
        //    CompanyPositionListVM cmCompanyPositions = _service.GetAllCompanyPositions().Result;
        //    //lblBreadcrumb.Text = $"{cmCompanyPositions.CareerMapVm.CareerMapName}";

        //    positions = new List<CompanyPositionVM>(cmCompanyPositions.CompanyPositionVmList);
        //}
        //catch (Exception)
        //{
        //    positions = new List<CompanyPositionVM>();
        //    ModelState.AddModelError(string.Empty, "Erro no servidor. Contate o Administrador.");
        //}

        //    return View("This is index");
        //}

        ////public ActionResult Index(int careerId) 
        ////{
        ////    IEnumerable<CompanyPositionVM> positions;
        ////    try
        ////    {
        ////        CompanyPositionListVM cmCompanyPositions = _service.GetAllCompanyPositions().Result;
        ////        //lblBreadcrumb.Text = $"{cmCompanyPositions.CareerMapVm.CareerMapName}";

        ////        positions = new List<CompanyPositionVM>(cmCompanyPositions.CompanyPositionVmList);
        ////    }
        ////    catch (Exception)
        ////    {
        ////        positions = new List<CompanyPositionVM>();
        ////        ModelState.AddModelError(string.Empty, "Erro no servidor. Contate o Administrador.");
        ////    }

        ////    return View(positions);
        ////}





        //public ActionResult Index0()
        //{
        //    //return View(_service);

        //    IEnumerable<CompanyPositionService> contatos = null;

        //    using (var client = new HttpClient())
        //    {
        //        client.BaseAddress = new Uri("https://localhost:7149/api/careerMaps/1/companyPositions");

        //        //HTTP GET
        //        var responseTask = client.GetAsync("contatos");
        //        responseTask.Wait();
        //        var result = responseTask.Result;

        //        if (result.IsSuccessStatusCode)
        //        {
        //            var readTask = result.Content.ReadAsAsync<IList<CompanyPositionService>>();
        //            readTask.Wait();
        //            contatos = readTask.Result;
        //        }
        //        else
        //        {
        //            contatos = Enumerable.Empty<CompanyPositionService>();
        //            ModelState.AddModelError(string.Empty, "Erro no servidor. Contate o Administrador.");
        //        }
        //        return View(contatos);
        //    }
        //}    

        //// GET: CompanyPositionController/Details/5
        //public ActionResult Informacao(int id)
        //{
        //    return View();
        //}

        //// GET: CompanyPositionController/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: CompanyPositionController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: CompanyPositionController/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: CompanyPositionController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: CompanyPositionController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: CompanyPositionController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

frontend/admin/admin/Views/Shared/Details.cshtml
@*@model IEnumerable<admin.ViewModels.CareerMapVM>
@{
    ViewBag.Title = "Index";
}*@
@*<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Desenvolvimento Backend</a></li>
        <li class="breadcrumb-item active" aria-current="page">Carreiras</li>
    </ol>
    <h1>Desenvolvimento Backend</h1>

    <button class="btn-details" onclick="location.href='@Url.Action("Informacao")'">Exibir</button>

     
    <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" id="redirecionar" onchange="irParaPagina()">  
        <option selected>Analista Júnior</option>
        <option value="/CareerMaps/Informacao">C#</option>
        <option value="carreiras.html">SQL</option>
        <option value="carreiras.html">AWS</option>
        <option value="carreiras.html">Java</option>
        <option value="/CareerMaps/Informacao">Azure</option>
    </select>
    <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" id="redirecionar" onchange="irParaPagina()">
        <option selected>Analista Pleno </option>
        <option value="carreiras.html">C#</option>
        <option value="carreiras.html">SQL</option>
        <option value="carreiras.html">AWS</option>
        <option value="carreiras.html">Java</option>
        <option value="/CareerMaps/Informacao">Azure</option>
    </select>
    <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" id="redirecionar" onchange="irParaPagina()">
        <option selected>Analista Senior</option>
        <option value="carreiras.html">C#</option>
        <option value="carreiras.html">SQL</option>
        <option value="carreiras.html">AWS</option>
        <option value="carreiras.html">Java</option>
        <option value="/CareerMaps/Informacao">Azure</option>
    </select>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <button class="btn btn-primary" type="button" onclick="history.back()">Button</button>
    </div>
</nav>*@

@*<script src="scripts/main.js"></script>
<script>
function irParaPagina() {
  var select = document.getElementById("redirecionar");
  var selectedOption = select.options[select.selectedIndex];
  if (selectedOption.value !== "") {
    window.location = selectedOption.value;
  }
}
CompanyPositionRequirementsVM
</script>*@


@model IEnumerable<admin.ViewModels.CompanyPositionVM >
@{
    ViewBag.Title = "Index";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">Desenvolvimento Backend</li>
    </ol>
    @*<h2>Mapa de Carreira</h2>*@
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <button class="btn btn-primary me-md-2" type="button">Adicionar Mapa</button>
    </div>
    <table class="table">
        <tr>
            <th>
                Id
            </th>
            <th>
                Career name
            </th>
            <th>
                Action
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CompanyPositionId )
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CompanyPositionName)
                </td>
                <td>
                    <button class="btn-details" onclick="location.href='@Url.Action("Informacao", new { id = item.CompanyPositionId })'">Exibir</button>
                </td>
            </tr>
        }
        <tr>
            <td>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            </td>
        </tr>
    </table>   
</nav>



<style>
.btn-details {
  background-color: #007bff;
  color: #fff;
  border: none;
  padding: 8px 8px;
  border-radius: 4px;
  cursor: pointer;
}

.btn-details:hover {
  background-color: #0069d9;
}
</style>


            

frontend/admin/admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/admin.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" asp-append-version="true" />
    <script src="https://cdn.datatables.net/plug-ins/1.11.3/i18n/pt_br.json"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @*                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">admin</a>
                *@                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                          aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CareerMaps" asp-action="Index">Mapas de Carreira</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CompanyPosition" asp-action="Index">Cargos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Requirements" asp-action="Index">Requisitos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - admin - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>
    <script>
        //$(document).ready(function () {
        //    $('.datatables').DataTable({
        //        language: {
        //           url: 'https://cdn.datatables.net/plug-ins/1.11.3/i18n/pt_br.json'
        //        },
        //        pageLength: 5,   
                
        //    });            
        //});

         $(document).ready(function () {
            $('.datatables').DataTable({
                dom: '<"d-flex justify-content-between"lf>t<"d-flex justify-content-between"ip>',
                language: {
                    url: 'https://cdn.datatables.net/plug-ins/1.11.3/i18n/pt_br.json'
                },
                pageLength: 5,
                "lengthMenu": [[5, 10, 25, 50, 100, -1], [5, 10, 25, 50, 100, "Tudo"]],
            });
        });

        

    </script>
</body>
</html>