frontend/admin/admin/Controllers/CareerMapsController.cs
using admin.Api.Model.Response;
using admin.Services;
using admin.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace admin.Controllers
{
    public class CareerMapsController : Controller
    {
        private CareerMapsService _service;

        public CareerMapsController()
        {
            _service = new CareerMapsService();
            
        }

        public ActionResult Index()
        {
            return View(_service.GetAllCareers());
        }

        public ActionResult CompanyPositionsCareerMapDetail(int careerMapId)
        {
            var ret = _service.LoadCompanyPositionsFromCareerMapId(careerMapId);
            return View(ret);
        }

        public ActionResult RequirementsCompanyPositionDetail(int careerMapId, int companyPositionId)
        {
            var ret = _service.LoadRequirementsFromCompanyPositionId(careerMapId, companyPositionId);
            return View(ret);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CareerMapResponse careerMap)
        {
            var ret = _service.Insert(careerMap);
            if (ret)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult AssociatePositions(int careerMapId)
        {
            var availablePositions = new List<CompanyPositionInfo>();
            var unavailablePositions = new List<CompanyPositionInfo>();
            var init = new CompanyPositionListResponse();
            var career = _service.GetAllCareers().Find(x => x.CareerMapId == careerMapId);

            if(career != null)
            {
                try
                {
                    var _serviceCompanyPosition = new CompanyPositionService();

                    var existingPositions = _service.LoadCompanyPositionsFromCareerMapId(careerMapId);
                    var all = _serviceCompanyPosition.GetAllPositions();

                    foreach (var pos in all)
                    {
                        var info = new CompanyPositionInfo()
                        {
                            CompanyPositionId = pos.CompanyPositionId,
                            CompanyPositionName = pos.CompanyPositionName
                        };

                        if (existingPositions.CompanyPositionResponseList.Find(x => x.CompanyPositionInfo.CompanyPositionId == pos.CompanyPositionId) != null)
                        {
                            unavailablePositions.Add(info);
                        }
                        else
                        {
                            availablePositions.Add(info);
                        }
                    }

                }
                catch (Exception) { /* throw; */ }
            }

            ViewBag.AvailablePositions = availablePositions;
            ViewBag.UnavailablePositions = unavailablePositions;

            init.CareerMapResponse = career == null ? new CareerMapResponse() : career;
            
            return View(init);
        }

        [HttpPost]
        public ActionResult AssociatePositions(CompanyPositionListResponse positions)
        {
            var ret = _service.AssociatePositions(positions);
            if (ret)
            {
                return RedirectToAction("CompanyPositionsCareerMapDetail", new { careerMapId = positions.CareerMapResponse.CareerMapId });
            }
            else
            {
                return View();
            }
        }
    }
}

frontend/admin/admin/Controllers/QuestionsController.cs
using admin.Api.Model;
using admin.Api.Service;
using admin.Services;
using admin.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace admin.Controllers
{
    public class QuestionsController : Controller
    {
        private Services.QuestionService _service { get; set; }

        public QuestionsController()
        {
            _service = new Services.QuestionService();
        }

        public ActionResult Details(int questionId)
        {
            return View(_service.GetQuestionById(questionId));
        }

        //public ActionResult Create(int testId)
        [HttpGet]
        public ActionResult Create(int testId)
        {
            //ViewBag.testId = testId;
            AddQuestionVm questionModel = new AddQuestionVm() { IdTest = testId };
            return View(questionModel);
        }

        //public ActionResult Create(QuestionsAlternative question)
        [HttpPost]
        public ActionResult Create(AddQuestionVm questionModel)
        {


            //var idTest = (Int32) ViewData["testId"];
            //ViewBag.testId = idTest;
            //, int testId

            //ViewBag.testId = 305;//testId;
            var res = _service.Insert(questionModel);

            if (res)
            {
                return RedirectToAction("Details", "Tests", new { testId = questionModel.IdTest});
            }

            return View(questionModel);
        }




        // GET: CarrermapsController
        //public ActionResult Index()
        //{
        //    return View(_service.GetAllRequirements());
        //}

        //[HttpGet]
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //[HttpPost]
        //public ActionResult Create(RequirementInfo requirement)
        //{
        //    var ret = _service.AddRequirement(requirement);
        //    if (ret)
        //    {
        //        return RedirectToAction("Index");
        //    }
        //    else
        //    {
        //        return View();
        //    }
        //}



        ////private CompanyPositionService _service { get; set; }

        //public RequirementsController()
        //{
        //_service = new CompanyPositionService();
        //}

        //// GET: CompanyPositionController
        //public ActionResult Index() 
        //{
        //IEnumerable<CompanyPositionVM> positions;
        //try
        //{
        //    CompanyPositionListVM cmCompanyPositions = _service.GetAllCompanyPositions().Result;
        //    //lblBreadcrumb.Text = $"{cmCompanyPositions.CareerMapVm.CareerMapName}";

        //    positions = new List<CompanyPositionVM>(cmCompanyPositions.CompanyPositionVmList);
        //}
        //catch (Exception)
        //{
        //    positions = new List<CompanyPositionVM>();
        //    ModelState.AddModelError(string.Empty, "Erro no servidor. Contate o Administrador.");
        //}

        //    return View("This is index");
        //}

        ////public ActionResult Index(int careerId) 
        ////{
        ////    IEnumerable<CompanyPositionVM> positions;
        ////    try
        ////    {
        ////        CompanyPositionListVM cmCompanyPositions = _service.GetAllCompanyPositions().Result;
        ////        //lblBreadcrumb.Text = $"{cmCompanyPositions.CareerMapVm.CareerMapName}";

        ////        positions = new List<CompanyPositionVM>(cmCompanyPositions.CompanyPositionVmList);
        ////    }
        ////    catch (Exception)
        ////    {
        ////        positions = new List<CompanyPositionVM>();
        ////        ModelState.AddModelError(string.Empty, "Erro no servidor. Contate o Administrador.");
        ////    }

        ////    return View(positions);
        ////}





        //public ActionResult Index0()
        //{
        //    //return View(_service);

        //    IEnumerable<CompanyPositionService> contatos = null;

        //    using (var client = new HttpClient())
        //    {
        //        client.BaseAddress = new Uri("https://localhost:7149/api/careerMaps/1/companyPositions");

        //        //HTTP GET
        //        var responseTask = client.GetAsync("contatos");
        //        responseTask.Wait();
        //        var result = responseTask.Result;

        //        if (result.IsSuccessStatusCode)
        //        {
        //            var readTask = result.Content.ReadAsAsync<IList<CompanyPositionService>>();
        //            readTask.Wait();
        //            contatos = readTask.Result;
        //        }
        //        else
        //        {
        //            contatos = Enumerable.Empty<CompanyPositionService>();
        //            ModelState.AddModelError(string.Empty, "Erro no servidor. Contate o Administrador.");
        //        }
        //        return View(contatos);
        //    }
        //}    

        //// GET: CompanyPositionController/Details/5
        //public ActionResult Informacao(int id)
        //{
        //    return View();
        //}

        //// GET: CompanyPositionController/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: CompanyPositionController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: CompanyPositionController/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: CompanyPositionController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: CompanyPositionController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: CompanyPositionController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

frontend/admin/admin/Controllers/TestsController.cs
using admin.Api.Model;
using admin.Api.Model.Response;
using admin.Api.Service;
using admin.Services;
using admin.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace admin.Controllers
{
    public class TestsController : Controller
    {
        private Services.TestService _service { get; set; }

        public TestsController()
        {
            _service = new Services.TestService();
        }


        // GET: CarrermapsController
        public ActionResult TestsByRequirement(int requirementId)
        {
            ViewBag.requirementId = requirementId;
            return View(_service.GetAllTestsByRequirementId(requirementId));
        }

        [HttpGet]
        public ActionResult Create(int requirementId)
        {
            ViewBag.requirementId = requirementId;
            return View();
        }

        [HttpPost]
        public ActionResult Create(MTest test)
        {
            var res = _service.Insert(test);

            if (res)
            {
                return RedirectToAction("TestsByRequirement", new { requirementId = test.RequirementId });
            }
            else
            {
                ViewBag.requirementId = test.RequirementId;
                return View();
            }
        }

        // GET: TestByID
        public ActionResult Details(int testId)
        {
            return View(_service.GetTestById(testId));
        }

        //[HttpPost]
        //public ActionResult Create(/*TestInfo test*/)
        //{
        //    //var ret = _service.AddTest(test);
        //    //if (ret)
        //    //{
        //    //    return RedirectToAction("Index");
        //    //}
        //    //else
        //    //{
        //        return View();
        //    //}
        //}



        ////private CompanyPositionService _service { get; set; }

        //public RequirementsController()
        //{
        //_service = new CompanyPositionService();
        //}

        //// GET: CompanyPositionController
        //public ActionResult Index() 
        //{
        //IEnumerable<CompanyPositionVM> positions;
        //try
        //{
        //    CompanyPositionListVM cmCompanyPositions = _service.GetAllCompanyPositions().Result;
        //    //lblBreadcrumb.Text = $"{cmCompanyPositions.CareerMapVm.CareerMapName}";

        //    positions = new List<CompanyPositionVM>(cmCompanyPositions.CompanyPositionVmList);
        //}
        //catch (Exception)
        //{
        //    positions = new List<CompanyPositionVM>();
        //    ModelState.AddModelError(string.Empty, "Erro no servidor. Contate o Administrador.");
        //}

        //    return View("This is index");
        //}

        ////public ActionResult Index(int careerId) 
        ////{
        ////    IEnumerable<CompanyPositionVM> positions;
        ////    try
        ////    {
        ////        CompanyPositionListVM cmCompanyPositions = _service.GetAllCompanyPositions().Result;
        ////        //lblBreadcrumb.Text = $"{cmCompanyPositions.CareerMapVm.CareerMapName}";

        ////        positions = new List<CompanyPositionVM>(cmCompanyPositions.CompanyPositionVmList);
        ////    }
        ////    catch (Exception)
        ////    {
        ////        positions = new List<CompanyPositionVM>();
        ////        ModelState.AddModelError(string.Empty, "Erro no servidor. Contate o Administrador.");
        ////    }

        ////    return View(positions);
        ////}





        //public ActionResult Index0()
        //{
        //    //return View(_service);

        //    IEnumerable<CompanyPositionService> contatos = null;

        //    using (var client = new HttpClient())
        //    {
        //        client.BaseAddress = new Uri("https://localhost:7149/api/careerMaps/1/companyPositions");

        //        //HTTP GET
        //        var responseTask = client.GetAsync("contatos");
        //        responseTask.Wait();
        //        var result = responseTask.Result;

        //        if (result.IsSuccessStatusCode)
        //        {
        //            var readTask = result.Content.ReadAsAsync<IList<CompanyPositionService>>();
        //            readTask.Wait();
        //            contatos = readTask.Result;
        //        }
        //        else
        //        {
        //            contatos = Enumerable.Empty<CompanyPositionService>();
        //            ModelState.AddModelError(string.Empty, "Erro no servidor. Contate o Administrador.");
        //        }
        //        return View(contatos);
        //    }
        //}    

        //// GET: CompanyPositionController/Details/5
        //public ActionResult Informacao(int id)
        //{
        //    return View();
        //}

        //// GET: CompanyPositionController/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: CompanyPositionController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: CompanyPositionController/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: CompanyPositionController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: CompanyPositionController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: CompanyPositionController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

frontend/admin/admin/Views/Tests/Create.cshtml
@model admin.Api.Model.MTest

@{
    ViewData["Title"] = "Create";
}

<h1>Criar</h1>

@*<h4>MTest</h4>*@
<hr />

<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-md-4">
            @*<div class="form-group">
            <label asp-for="TestId" class="control-label"></label>

            <input asp-for="TestId" class="form-control" />
            <span asp-validation-for="TestId" class="text-danger"></span>
            </div>
            <div class="form-group">
            <label asp-for="RequirementId" class="control-label"></label>
            <input asp-for="RequirementId" class="form-control" />
            <span asp-validation-for="RequirementId" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                @Html.HiddenFor(x => x.RequirementId)
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">                
                <input type="submit" value="Create" class="btn btn-md btn-success col-md-5" />
                <a class="btn btn-md btn-outline-danger col-md-5" asp-action="Details" asp-controller="Tests" >Cancelar</a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

frontend/admin/admin/Views/Tests/Details.cshtml
@model admin.Api.Model.Response.TestEntireResponse

@{
    //ViewBag.Title = "Carreira - " + Model.CareerMapResponse.CareerMapName;
    ViewData["Title"] = Model.Description;
}

<h4>Questões do teste</h4>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item "><a href="@Url.Action("Index", "CareerMaps")">Mapas de carreira</a></li>
        @*<li class="breadcrumb-item"><a href="@Url.Action("CompanyPositionsCareerMapDetail", "CareerMaps", new { careerMapId = f.Model.CareerMap.CareerMapId })">@Model.CareerMap.CareerMapName</a></li>*@
        <li class="breadcrumb-item active">@Model.Description</li>
    </ol>
</nav>

<div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <button class="btn btn-outline-success me-md-2" type="button" onclick="location.href='@Url.Action("Create", "Questions", new { testId = Model.TestId })'"
            @*, new{ testId = Model.TestId}*@>
        Adicionar Questão
    </button>
</div>

<table class="table table-striped datatables">
    <thead>
        <tr>
            @*            <th>
            @Html.DisplayNameFor(model => model.QuestionsAlternatives.FirstOrDefault().QuestionId)
            </th>
            *@
            <th class="w-50">
                @Html.DisplayNameFor(model => model.QuestionsAlternatives.FirstOrDefault().Question)
            </th>
            <th class="w-25">
                @Html.DisplayNameFor(model => model.QuestionsAlternatives.FirstOrDefault().Type)
            </th>
            <th class="w-25">
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.QuestionsAlternatives)
        {
            <tr>
                <td>
                    @Html.HiddenFor(modelItem => item.QuestionId)
                    @Html.DisplayFor(modelItem => item.Question)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type.QuestionTypeName)
                </td>
                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |*@
                    @*@Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |*@
                    @*@Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@

                    <button class="btn btn-outline-info btn-sm" onclick="location.href='@Url.Action("Details", "Questions", new {  questionId=item.QuestionId })'">Vizualizar</button>

                    @*@Html.ActionLink("Visualizar", "Details", "Questions", new {  questionId=item.QuestionId })*@
                </td>
            </tr>
        }
    </tbody>
</table>

frontend/admin/admin/Views/Tests/TestsByRequirement.cshtml
@model IEnumerable<admin.Api.Model.Response.TestEntireResponse>

@{
    //ViewBag.Title = "Carreira - " + Model.CareerMapResponse.CareerMapName;
    //var f = Model.FirstOrDefault();
    //ViewData["Title"] = Model.FirstOrDefault().Description;

    var requirementName = "";
    if(
        Model != null && 
        Model.Count() > 0 &&
        Model.First() != null &&
        Model.First().Requirement != null && 
        Model.First().Requirement.RequirementName != null
    )
    {
        requirementName = Model.FirstOrDefault().Requirement.RequirementName;
    }

}

<h4>Testes do requisito</h4>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item "><a href="@Url.Action("Index", "CareerMaps")">Mapas de carreira</a></li>
        @*<li class="breadcrumb-item"><a href="@Url.Action("CompanyPositionsCareerMapDetail", "CareerMaps", new { careerMapId = f.Model.CareerMap.CareerMapId })">@Model.CareerMap.CareerMapName</a></li>*@
        @*<li class="breadcrumb-item active">@Model.FirstOrDefault().Description</li>*@
        <li class="breadcrumb-item active">@requirementName</li>
    </ol>
</nav>

<div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <button class="btn btn-outline-success me-md-2" type="button" onclick="location.href='@Url.Action("Create", new{ requirementId = ViewBag.requirementId})'">Adicionar Teste</button>
</div>

<table class="table table-striped datatables">
    <thead>
        <tr>
            <th>
                @*@Html.DisplayNameFor(model => model.Description)*@
                @Html.DisplayName("Descrição")
            </th>
            <th class="w-25"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) 
        {
        <tr>
            <td>
                @Html.HiddenFor(modelItem => item.TestId)
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { /*id=item.TestId*/ }) |*@

                    <button class="btn btn-outline-info btn-sm" onclick="location.href='@Url.Action("Details", new { testId=item.TestId })'">Questões</button>
                    @*@Html.ActionLink("Teste", "Details", new { testId=item.TestId })*@


                @*| @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
            </td>
        </tr>
        }
    </tbody>
</table>